### ISSUE TITLE
Github登录好像不行了

### ISSUE THREAD

**Issue by zxmacc** [walinejs/auth#1]
![img1](https://user-images.githubusercontent.com/71143103/147942067-9a34942b-4488-4944-b36b-d82e573b0431.png)
另外两个好像都行，waline本体部署在轻服务，环境变量都是默认，什么都动过，就自己注册了一个账号。加速器也关掉过试了

**Comment by zxmacc** [comment]
https://yanya-waline.app.cloudendpoint.cn/

**Comment by lizheming** [comment]
这个是已知问题，是轻服务环境的问题，节后我咨询下他们

**Comment by zxmacc** [comment]
好的，谢谢
